In [58]:
# ! pip install datetime
# ! pip install numpy



[notice] A new release of pip is available: 24.2 -> 24.3.1
[notice] To update, run: python.exe -m pip install --upgrade pip



[notice] A new release of pip is available: 24.2 -> 24.3.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [1]:
import numpy as np

# Solicitar um número de 4 dígitos
numero = int(input("Digite um número de 4 dígitos: "))

# Converter o número para uma string
numero_str = str(numero)

# Criar um array numpy com os dígitos
array_digitos = np.array([int(digito) for digito in numero_str])

# Exibir o array
print("Array com os dígitos:", array_digitos)


Array com os dígitos: [2 8 1 7]


In [2]:
from datetime import date
import numpy as np

#concurso = int(input('Digite o concurso: '))
concurso = 2815
# Converter o número para uma string
concurso_str = str(concurso)
concurso_array_digitos = np.array([int(digito) for digito in concurso_str])

# Exibir o array
print("Número do concurso:", concurso_array_digitos)

data_atual = date.today()
data_em_texto = '{}/{}/{}'.format(data_atual.day, data_atual.month, data_atual.year)

ano_string = str(data_atual.year)
# Criar um array de números inteiros a partir dos dígitos do ano
digitos_ano_atual = np.array([int(digito) for digito in str(ano_string)])


array_hoje = np.concatenate(([data_atual.day, data_atual.month], digitos_ano_atual))

print(f'Data atual {array_hoje}')


#dia_nasc = int(input("Digite sua dia do nascimento:"))
#mes_nasc = int(input("Digite o mês de nascimento:"))
#ano_nasc = int(input("Digite o ano de nascimento:"))

dia_nasc = int(4)
mes_nasc = int(2)
ano_nasc = int(1967)


# Criar um array de números inteiros a partir dos dígitos do ano
digitos_ano_nasc = np.array([int(digito) for digito in str(ano_nasc)])
array_data_nasc = np.concatenate(([dia_nasc, mes_nasc], digitos_ano_nasc))
print(f'Data de nascimento {array_data_nasc}')


numeros_do_sorteio = np.concatenate((concurso_array_digitos, array_hoje , array_data_nasc))
print(f'Junção dos 3 arrays - {numeros_do_sorteio}')


# Somar os elementos de dois em dois, considerando que o último elemento é somado a 0
somas_2 = numeros_do_sorteio[::2] + numeros_do_sorteio[1::2]

# Se o tamanho do array for ímpar, somar o último elemento com 0
if len(numeros_do_sorteio) % 2 != 0:
    somas_2 = np.append(somas_2, numeros_do_sorteio[-1])

# Exibir o resultado
#print("Somas de dois em dois (com último elemento separado):", somas_2)

# Somar os elementos de três em três
# Dividindo os elementos em blocos de tamanho 3
blocos = np.array_split(numeros_do_sorteio, np.ceil(len(numeros_do_sorteio) / 3))

# Somando os elementos de cada bloco
somas_3 = [np.sum(bloco) for bloco in blocos]

#print("Somas de três em três:", somas_3)


numeros_soma2_soma3 = np.concatenate((somas_2, somas_3))
#print(f'Números soma2 e soma3 {numeros_soma2_soma3}')

# Dividindo os elementos em blocos de tamanho 4
blocos = np.array_split(numeros_do_sorteio, np.ceil(len(numeros_do_sorteio) / 4))

# Somando os elementos de cada bloco
somas_4 = [np.sum(bloco) for bloco in blocos]

#print("Somas de quatro em quatro:", somas_4)


numeros_soma2_soma3_soma4 = np.concatenate((numeros_soma2_soma3, somas_4 ))
#print(f'Números soma2 e soma3 e soma4{numeros_soma2_soma3_soma4}')

# Dividindo os elementos em blocos de tamanho 2
blocos = np.array_split(numeros_soma2_soma3_soma4, np.ceil(len(numeros_soma2_soma3_soma4) / 2))

# Somando os elementos de cada bloco
somas_2_novamente = [np.sum(bloco) for bloco in blocos]

#print("Somas de três em três:", somas_2_novamente)

numeros_soma2_soma3_soma4_soma_2 = np.concatenate((numeros_soma2_soma3_soma4, somas_2_novamente))

# Dividindo os elementos em blocos de tamanho 3
blocos = np.array_split(numeros_soma2_soma3_soma4_soma_2, np.ceil(len(numeros_soma2_soma3_soma4_soma_2) / 3))

# Somando os elementos de cada bloco
somas_3_novamente = [np.sum(bloco) for bloco in blocos]

#print("Somas de três em três:", somas_3_novamente)


numeros_soma2_soma3_soma4_soma_2_soma_3 = np.concatenate((numeros_soma2_soma3_soma4_soma_2, somas_3_novamente))
print(f'Números soma2, soma3, soma4, soma2(novamente) e de 3(novamente) no resultado {numeros_soma2_soma3_soma4_soma_2_soma_3}')

# Filtrar os números menores ou iguais a 60
numeros_validos = numeros_soma2_soma3_soma4_soma_2_soma_3[numeros_soma2_soma3_soma4_soma_2_soma_3 <= 60]

# Gerar 6 números aleatórios únicos
cont = 1
while cont <= 3:
    numeros_aleatorios = np.random.choice(numeros_validos, size=6, replace=False)
    print(numeros_aleatorios)
    cont += 1




#rng = np.random.default_rng()
#numeros_possiveis = rng.integers(numeros_do_sorteio, size=6)
#print(numeros_possiveis)



#rng = np.random.default_rng(seed=42) #seed=42 trava a resposta
#rng = np.random.default_rng()
#numeros_possiveis = rng.integers(low=np.min(1), high=np.max(61), size=6)


Número do concurso: [2 8 1 5]
Data atual [16  1  2  0  2  5]
Data de nascimento [4 2 1 9 6 7]
Junção dos 3 arrays - [ 2  8  1  5 16  1  2  0  2  5  4  2  1  9  6  7]
Números soma2, soma3, soma4, soma2(novamente) e de 3(novamente) no resultado [10  6 17  2  7  6 10 13 11 22  4 11 10 13 16 19 13 23 16 19 13 23 33 15
 23 35 36 33 15 34 37 39 55 48 71 94]
[33 34 22  6 23 35]
[55 15 33 22 23 35]
[37 35 11 34 15  4]


Sem minha data de aniversário

In [5]:
from datetime import date
import numpy as np

concurso = int(input('Digite o concurso: '))
#concurso = 2815
# Converter o número para uma string
concurso_str = str(concurso)
concurso_array_digitos = np.array([int(digito) for digito in concurso_str])

# Exibir o array
print("Número do concurso:", concurso_array_digitos)
soma_concurso = np.sum(concurso_array_digitos)
print("Soma dos numeros do concurso:", soma_concurso)

data_atual = date.today()
data_em_texto = '{}/{}/{}'.format(data_atual.day, data_atual.month, data_atual.year)

ano_string = str(data_atual.year)
# Criar um array de números inteiros a partir dos dígitos do ano
digitos_ano_atual = np.array([int(digito) for digito in str(ano_string)])


array_hoje = np.concatenate(([data_atual.day, data_atual.month], digitos_ano_atual))

print(f'Data atual: {array_hoje}')

soma_data_atual = np.sum(array_hoje)
print("Soma dos numeros da data atual:", soma_data_atual)

soma_concurso_data_atual = np.array([soma_concurso, soma_data_atual])
numeros_do_sorteio = np.concatenate((concurso_array_digitos, array_hoje, soma_concurso_data_atual))
print(f'Junção dos 2 arrays (concurso e data) e soma da data e soma do número do sorteio:  {numeros_do_sorteio}')

# Função genérica para somar em blocos de tamanho n
def somar_em_blocos(array, bloco):
    return np.array([np.sum(array[i:i+bloco]) for i in range(0, len(array), bloco)])

# Soma de dois em dois
soma_2 = somar_em_blocos(numeros_do_sorteio, 2)
print("Soma de dois em dois:", soma_2)

# Soma de três em três
soma_3 = somar_em_blocos(numeros_do_sorteio, 3)
print("Soma de três em três:", soma_3)

# Soma de quatro em quatro
soma_4 = somar_em_blocos(numeros_do_sorteio, 4)
print("Soma de quatro em quatro:", soma_4)

# Soma de cinco em cinco
soma_5 = somar_em_blocos(numeros_do_sorteio, 5)
print("Soma de cinco em cinco:", soma_5)

# Soma de seis em seis
soma_6 = somar_em_blocos(numeros_do_sorteio, 6)
print("Soma de seis em seis:", soma_6)



juncao_listas_6 = np.concatenate((numeros_do_sorteio, soma_2, soma_3, soma_4, soma_5, soma_6 ))
print(f'Junção listas ate de 6 em 6 {juncao_listas_6}')

# Soma de sete em sete
soma_7 = somar_em_blocos(juncao_listas_6, 7)
for numero in soma_7:
    indice = np.where(soma_7 == numero)
    while numero > 60:
       numero -= data_atual.day
       soma_7[indice] = numero       
       continue
    else:
       
       continue

    

print("Soma de sete em sete a lista juntada:", soma_7)

juncao_listas = np.concatenate((juncao_listas_6, soma_7))

print(f'Junção de todas as listas: {juncao_listas }')

numeros_validos = np.unique(juncao_listas)

# Filtrar os números menores ou iguais a 60 e maior que 0
numeros_validos = juncao_listas[juncao_listas > 0]
numeros_validos = juncao_listas[juncao_listas <= 60]
print(f'Números válidos >0 e <= 60 {numeros_validos}')

# Gerar 6 números aleatórios únicos
cont = 1
print(f'*** Três opçoes de jogos - Concurso: {concurso} ***' )
while cont <= 3:
    numeros_aleatorios = np.random.choice(numeros_validos, size=6, replace=False)
    numeros_ordenados = np.sort(numeros_aleatorios)
    print(numeros_ordenados)
    cont += 1
else:
    print('****************************************************')  

Número do concurso: [2 7 1 6]
Soma dos numeros do concurso: 16
Data atual: [16  1  2  0  2  5]
Soma dos numeros da data atual: 26
Junção dos 2 arrays (concurso e data) e soma da data e soma do número do sorteio:  [ 2  7  1  6 16  1  2  0  2  5 16 26]
Soma de dois em dois: [ 9  7 17  2  7 42]
Soma de três em três: [10 23  4 47]
Soma de quatro em quatro: [16 19 49]
Soma de cinco em cinco: [32 10 42]
Soma de seis em seis: [33 51]
Junção listas ate de 6 em 6 [ 2  7  1  6 16  1  2  0  2  5 16 26  9  7 17  2  7 42 10 23  4 47 16 19
 49 32 10 42 33 51]
Soma de sete em sete a lista juntada: [35 49 57 55 52]
Junção de todas as listas: [ 2  7  1  6 16  1  2  0  2  5 16 26  9  7 17  2  7 42 10 23  4 47 16 19
 49 32 10 42 33 51 35 49 57 55 52]
Números válidos >0 e <= 60 [ 2  7  1  6 16  1  2  0  2  5 16 26  9  7 17  2  7 42 10 23  4 47 16 19
 49 32 10 42 33 51 35 49 57 55 52]
*** Três opçoes de jogos - Concurso: 2716 ***
[ 2  5  6 10 52 55]
[ 1  7 16 19 26 49]
[ 1  9 16 16 19 33]
*****************

2616 29/07/2023  

#### ultimo digito = 06
#### penultimo e ultimo  = 16
#### day - ultimo concurso   = 23
#### day + month  - penunltimo concurso (1)  = 35
#### day + month + 1 concurso (2) = 38
#### soma concurso 26 + 16 = 42 + mes(05) = 49

## Resutado da simulação
### Número do concurso: [2 8 1 6]
### 16/1/2025
### [ 6 21 28 29 46 47]

## Resultado oficial 
### 04, 17, 19, 20, 40, 48